version: '3'

services:
  geography-db:
    container_name: db
    hostname: geography-db
    build: 01_DB/.
    ports:
      - '27017:27017'
  geography-server:
    container_name: server
    build:
      context: 02_Server/.
      dockerfile: Dockerfile.compose
    depends_on:
      - geography-db
    ports:
      - '4000:4000'
    command: sh wait-mongo.sh
    environment:
      - MONGODB_URL=mongodb://admin:admin@geography-db:27017/geographydb?authSource=admin
  geography-frontend:
    container_name: frontend
    hostname: geography-frontend
    build:
      context: 03_Client/geo-ui
      dockerfile: Dockerfile.compose
    depends_on:
      - geography-server
    ports:
      - '3000:3000'
