version: '3'

services:
  geography-db:
    container_name: geography-db
    hostname: geography-db
    image: yemax/geography-mongodb:v1
    ports:
      - "27017:27017"
  geography-server:
    container_name: geography-server
    image: yemax/geography-api:v1
    depends_on:
      - geography-db
    ports:
      - "4000:4000"