name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set tag
      run: echo "tag_name=(date +%s)"
      
    - name: Build the Docker image
      shell: bash
      run: |
        cd ./01_DB
        docker build . --file Dockerfile.single --tag geo-db:$(tag_name)

    - name: Push Docker image to Docker.Hub
      run: |
        docker push geo-db:$(tag_name)
