name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set tag 
      run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV
      
    - name: Docker login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build the Docker image
      shell: bash
      
      run: |
       cd 01_DB
       docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/geo-db:$TAG_NAME
       
    - name: Push Docker image to Docker.Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/geo-db:$TAG_NAME
      
      
