name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set tag 
      run: export tag _name=$(date +%$)
    
    - name: Build the Docker image
      shell: bash
      
      run: |
       cd 01_DB
       docker build . --file Dockerfile --tag geo-db:$(date +%s)
       
    - name: Push Docker image to Docker.Hub
      run: docker push geo-db:$tag _name
      
      
      
